spring:
  application:
    name: "Akdemia DBHStudios"
    url: "http://localhost"

  datasource:
    url: 'jdbc:h2:mem:BDD_AKDEMIA;INIT=CREATE SCHEMA IF NOT EXISTS BDD_AKDEMIA;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password:

  messages:
    basename: "i18n/messages"
  jpa:
    generate-ddl: true #change to false in production mode
    hibernate:
      ddl-auto: create-drop #change to validate in production mode
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: 'BDD_AKDMVM'
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2


browser: "chrome"
screenshot:
  path: "target/"
logging:
  level:
    com.diegobarrioh.akdemia: DEBUG

