spring:
  datasource:
    url: 'jdbc:h2:mem:BDD_AKDEMIA;INIT=CREATE SCHEMA IF NOT EXISTS BDD_AKDEMIA;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password:
  jpa:
    generate-ddl: true #change to false in production mode
    hibernate:
      ddl-auto: create #change to validate in production mode
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_schema: 'BDD_AKDEMIA'
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      platform: h2


logging:
  level:
    com.diegobarrioh.akdemia: DEBUG