spring:
  datasource:
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_SCHEMA:BDD_AKDEMIA}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:secret}
  sql:
    init:
      mode: never
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate #change to validate in production mode
    generate-ddl: true #change to false in production mode
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
        default_schema: ${DB_SCHEMA:BDD_AKDEMIA}



  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

logging:
  level:
    com.diegobarrioh.akdemia: DEBUG

storage:
  location: '/Users/diegobarrioh/code/java/ak.demia/src/main/resources/upload-dir'