spring:
  application:
    name: "Akdemia DBHStudios"
    url: "http://localhost"

  datasource:
    url: 'jdbc:h2:mem:BDD_AKDMIA;INIT=CREATE SCHEMA IF NOT EXISTS BDD_AKDMIA;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    username: 'sa'
    password:

  messages:
    basename: "i18n/messages"

browser: "chrome"
screenshot:
  path: "target/"